[package]
name = "filesharing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmtorrent = { path = '../../'}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.32"

[dependencies.web-sys]
features = [
    "RtcDataChannel",
]
